services:
  - type: web
    name: telegram-file-converter-bot
    env: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MAX_FILE_SIZE_MB
        value: "20"
      - key: ADMIN_ID
        sync: false
    healthCheckPath: /
